config/routes.rb
Snippets::Engine.routes.draw do
  resources :snippets do
    collection do
      get :search
    end
  end

  root to: 'snippets#index'
end

app/models/snippets/search.rb
module Snippets
  class Search
    extend ActiveModel::Naming
    include ActiveModel::AttributeMethods
    include ActiveModel::Conversion

    class << self
      def attributes
        @attributes
      end

      def search_attributes(attributes = [])
        @attributes = attributes
        send(:attr_accessor, *@attributes)
      end
    end

    search_attributes [:key, :value]

    def initialize(attributes = {})
      attributes ||= {}
      attributes.each do |k, v|
        send(:"#{k}=", v)
      end
    end

    def perform_search?
      self.class.attributes.any? { |a| send(a).present? }
    end

    def persisted?
      false
    end
  end
end

app/models/snippets/snippet.rb
module Snippets
  class Snippet < ActiveRecord::Base
    validates :key, :value, presence: true
    validates :key, uniqueness: true

    before_save :cache
    before_destroy :clear_cache
    after_save :clear_view_cache_records

    class << self
      def all_with_defaults
        (all + Snippets::SnippetDefaults.all).uniq(&:key).sort_by!(&:key)
      end

      def cache_all
        all.map(&:cache)
      end

      def view_cache_record_list(key)
        Redis::List.new(key)
      end

      def store_view_cache_record(key, value)
        unless view_cache_record_list(key).include?(value) || key.blank?
          view_cache_record_list(key) << value
        end
      end
    end

    def cache
      store_value(key_was, nil) if key_changed?
      store_value(key, value)
    end

    def clear_cache
      store_value(key, nil)
    end

    def view_cache_records
      Snippet.view_cache_record_list(key)
    end

    def clear_view_cache_records
      view_cache_records.each do |key|
        Rails.cache.delete(key)
      end
    end

    private

    def store_value(key, value)
      I18n.backend.store_translations(
        I18n.default_locale,
        { key => value },
        escape: false
      )
    end
  end
end

app/models/snippets/snippet_defaults.rb
module Snippets
  class SnippetDefaults < SimpleDelegator
    class << self
      def all
        @snippets ||= (
          snippets = default_snippets
          snippets = flatten_snippets(snippets)
          mapped_snippets(snippets)
        )
      end

      private

      def backend
        @backend ||= (
          backend = I18n::Backend::Simple.new
          backend.load_translations(
            Dir[Rails.root.join(Snippets.defaults_load_path)]
          )
          backend
        )
      end

      def default_snippets
        backend.send(:translations)[I18n.default_locale]
      end

      def flatten_snippets(snippets)
        to_shallow_hash(snippets)
      end

      def mapped_snippets(snippets)
        snippets.map { |k, v| Snippet.new(key: k, value: v) }
      end

      # From https://github.com/mynewsdesk/translate
      def to_shallow_hash(hash)
        hash ||= {}

        hash.each_with_object({}) do |(key, value), shallow_hash|
          if value.is_a?(Hash)
            to_shallow_hash(value).each do |sub_key, sub_value|
              shallow_hash[[key, sub_key].join('.')] = sub_value
            end
          else
            shallow_hash[key.to_s] = value
          end
          shallow_hash
        end
      end
    end
  end
end

app/controllers/snippets/application_controller.rb
ApplicationController.class_eval do
  helper Snippets::SnippetsHelper
end

class Snippets::ApplicationController < ApplicationController
  respond_to :html
  layout -> { Snippets.layout }
end

app/controllers/snippets/snippets_controller.rb
module Snippets
  class SnippetsController < ApplicationController
    before_action :set_search, only: [:index, :search]
    before_action :set_snippet, only: [:edit, :update, :destroy]
    after_action :store_params, only: [:index]

    def index
      @snippets = Kaminari.paginate_array(
        Snippet.all_with_defaults
      ).page(params[:page])

      respond_with @snippets
    end

    def search
      @snippets = Kaminari.paginate_array(
        Snippet.search(@search)
      ).page(params[:page])

      respond_with @snippets do |f|
        f.html { render :index }
      end
    end

    def new
      @snippet = Snippet.new(new_params)
      respond_with @snippet
    end

    def edit
      respond_with @snippet
    end

    def create
      @snippet = Snippet.new(snippet_params)

      if @snippet.save
        respond_with @snippet do |f|
          f.html do
            redirect_to snippets_path(redirect_params),
              notice: t('.successful')
          end
        end
      else
        respond_with @snippet, status: :unprocessable_entity do |f|
          f.html { render :new }
        end
      end
    end

    def update
      if @snippet.update(snippet_params)
        respond_with @snippet do |f|
          f.html do
            redirect_to snippets_path(redirect_params),
              notice: t('.successful')
          end
        end
      else
        respond_with @snippet, status: :unprocessable_entity do |f|
          f.html { render :edit }
        end
      end
    end

    def destroy
      @snippet.destroy
      redirect_to snippets_path(redirect_params),
        notice: t('.successful')
    end

    private

    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    def set_search
      @search = if params[:search].present?
                  Search.new(search_params)
                else
                  Search.new
                end
    end

    def store_params
      session[:stored_params] = {
        page: params[:page]
      }
    end
    
    def redirect_params(params = {})
      params ||= {}
      (session[:stored_params] || {}).merge(params)
    end

    def allowed_params
      %i(key value)
    end

    def new_params
      params.permit(allowed_params)
    end

    def snippet_params
      params.require(:snippet).permit(allowed_params)
    end

    def search_params
      params.require(:search).permit(:key, :value)
    end
  end
end

app/helpers/snippets/application_helper.rb
module Snippets
  module ApplicationHelper
  end
end

app/helpers/snippets/snippets_helper.rb
module Snippets
  module SnippetsHelper
  end
end

app/views/snippets/snippets/_form.html.haml
= simple_form_for snippet do |f|
  = f.error_notification

  %fieldset
    = f.input :key, disabled: true
    = f.input :key, as: :hidden
    = f.input :value, input_html: { class: 'markdown-editor' }

  %fieldset.buttons
    = f.button :submit

%h2= t('.cache_records.title')
= simple_format t('.cache_records.blurb')

%ul
  - @snippet.view_cache_records.each do |cache_key|
    %li= cache_key

app/views/snippets/snippets/edit.html.haml
%h1= t('.heading')

= render 'form', snippet: @snippet

= link_to t('.back'), snippets_path

app/views/snippets/snippets/index.html.haml
%h1= t('.heading')

%section.snippets-index
  = simple_form_for @search, url: search_snippets_path, method: :get do |f|
    %table
      %thead
        %tr
          %th= t('.table.key')
          %th= t('.table.value')
          %th= t('.table.actions')

        %tr
          %td= f.input :key, required: false
          %td= f.input :value, required: false
          %td= f.button :submit

      %tbody
        - @snippets.each do |snippet|
          %tr
            %td= snippet.key
            %td= truncate(snippet.value, length: 80)
            %td
              - if snippet.persisted?
                = link_to t('.actions.edit'),
                  edit_snippet_path(snippet), class: 'button'

                = link_to t('.actions.reset'),
                  snippet_path(snippet),
                  class: 'button',
                  method: :delete,
                  data: { confirm: t('.actions.confirm') }
              - else
                = link_to t('.actions.edit'),
                  new_snippet_path(key: snippet.key, value: snippet.value),
                  class: 'button'

  = paginate @snippets

app/views/snippets/snippets/new.html.haml
%h1= t('.heading')

= render 'form', snippet: @snippet

= link_to t('.back'), snippets_path